project_id = "mlbzdxsumfudrtuuybqn"

[functions.ai-chat]
verify_jwt = false

[functions.auth-email-handler]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.transition-pre-next-week]
verify_jwt = false