project_id = "mlbzdxsumfudrtuuybqn"

[functions.auto-translate]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.auth-email-handler]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.weekly-contest-transition]
verify_jwt = false