# Dependency Review Workflow
# 
# This Action will scan dependency manifest files that change as part of a Pull Request,
# surfacing known-vulnerable versions of the packages declared or updated in the PR.
# Once installed, if the workflow run is marked as required, PRs introducing known-vulnerable
# packages will be blocked from merging.
#
# Source repository: https://github.com/actions/dependency-review-action

name: 'Dependency Review'

on:
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          # Fail the action if vulnerabilities are found
          fail-on-severity: moderate
          # Deny licenses that are not compatible with open source
          deny-licenses: GPL-3.0, AGPL-3.0
          # Optional: Add a comment to the PR with the results
          comment-summary-in-pr: true
          # Optional: Only warn on vulnerabilities, don't fail the build
          # fail-on-severity: critical
