# Secret Scanning Workflow
#
# This workflow scans for accidentally committed secrets, API keys, tokens, and other sensitive data.
# It runs on every push and pull request to prevent secrets from being committed to the repository.
#
# Uses Gitleaks: https://github.com/gitleaks/gitleaks

name: 'Secret Scan'

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for accurate scanning
          
      - name: 'Run Gitleaks Secret Scanner'
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # Optional: for Gitleaks Pro features
          
  trufflehog-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: 'Run TruffleHog Secret Scanner'
        continue-on-error: true
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
